STATE_RES_NAME: "aws_ec2_info"
ec2_region: "us-east-1"
ec2_instance_type: "t2.micro"
ec2_image: "ami-04681a1dbd79675a5"
ec2_keypair: "ger-key_pair"
ec2_volume_size: "40"
ec2_count: "1"
ec2_security_group_id: "sg-0b64b4b02b6288761"
ec2_subnet_id: "subnet-65b9ab3f"
ec2_tag_Type: "t2.micro"
ec2_tag_Role: "ger-test-test"